### ISSUE TITLE
Dnet issues

### ISSUE THREAD

**Issue by Bry-fi** [nottinghamprisateam/pyersinia#7]
Collecting dnet (from -r requirements.txt (line 8))
  Could not find a version that satisfies the requirement dnet (from -r requirements.txt (line 8)) (from versions: )
No matching distribution found for dnet (from -r requirements.txt (line 8))

This app was tested on kali linux 2.0 and this app will not work without the dnet which is not found.

**Comment by dankitan** [comment]
dnet is necessary to run scapy in OS X. In kali linux is not necessary.
